http:
  port: "8081"

walmart:
  host: "walmart.p.rapidapi.com"
  port: "443"
  protocol: "HTTPS"
  basepath: "/"
  RapidapiHost: "walmart.p.rapidapi.com"
  RapidapiKey: "6618425f0emsh0ac43db2fa2dc86p1a82e7jsnefd5d8502dec"
  
db:
 user: "c4ebatch5"
 password: "![eD2GXmVhh/bvNic38T8XYA==]"
 database: "testdbc45"
 host: "db4free.net"
 port: "3306"
 